GENERAL:
  experiment: dental20000
  seed: 123

DATA:
  root_dir: ../datasets/dental20000
  batch_size: 1      # batchsize per gpu
  suffix: .pth
  num_points: 20000    # sample
  # augmentation
  augmentation: True

STRUCTURE:
  k: 16
  input_channels: 15
  output_channels: 17
  n_edgeconvs_backbone: 5
  emb_dims: 1024
  global_pool_backbone: avg   # max or avg
  norm: instance
  use_stn: False # spatial transformer network
  dynamic: False
  dropout: 0.

TRAIN:
  max_epochs: 10
  weight_decay: 0.0001
  delta: 0.1667
  load_from_checkpoint:
  resume_from_checkpoint:

  # one cycle lr scheduler
  lr_max: 0.001
  pct_start: 0.1    # percentage of the cycle spent increasing lr
  div_factor: 25    # determine the initial lr (lr_max / div_factor)
  final_div_factor: 1e4   # determine the final lr (lr_max / final_div_factor)
  start_epoch: 0

  train_folder: train
  train_workers: 4

  val_workers: 4
  val_folder: val

  test_workers: 4
  test_folder: val
